drop table if exists public.empresa_fiscais cascade;
drop table if exists public.fiscais cascade;

alter table public.usuarios
  add column if not exists auth_user_id uuid null references auth.users(id) on delete set null;

create unique index if not exists usuarios_auth_user_id_uidx
  on public.usuarios(auth_user_id)
  where auth_user_id is not null;

create table if not exists public.fiscais (
  id bigint generated by default as identity primary key,
  usuario_id bigint null references public.usuarios(id) on delete set null,
  auth_user_id uuid null references auth.users(id) on delete set null,
  nome text not null,
  email text null,
  matricula text null,
  telefone text null,
  setor text null,
  status text not null default 'sem_acesso' check (status in ('sem_acesso', 'com_acesso', 'inativo')),
  ativo boolean not null default true,
  data_fim timestamptz null,
  motivo_inativacao text null,
  substituto_id bigint null references public.fiscais(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.empresa_fiscais (
  empresa_id bigint not null references public.companies(id) on delete cascade,
  fiscal_id bigint not null references public.fiscais(id) on delete cascade,
  ativo boolean not null default true,
  data_inicio timestamptz not null default now(),
  data_fim timestamptz null,
  created_at timestamptz not null default now(),
  primary key (empresa_id, fiscal_id, data_inicio)
);

create index if not exists fiscais_usuario_id_idx on public.fiscais(usuario_id);
create index if not exists fiscais_auth_user_id_idx on public.fiscais(auth_user_id);
create index if not exists fiscais_status_idx on public.fiscais(status);
create index if not exists fiscais_email_idx on public.fiscais(lower(email));
create index if not exists empresa_fiscais_empresa_id_idx on public.empresa_fiscais(empresa_id);
create index if not exists empresa_fiscais_fiscal_id_idx on public.empresa_fiscais(fiscal_id);
create index if not exists empresa_fiscais_ativo_idx on public.empresa_fiscais(ativo);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_fiscais_updated_at on public.fiscais;
create trigger touch_fiscais_updated_at before update on public.fiscais
for each row execute function public.touch_updated_at();

alter table public.fiscais enable row level security;
alter table public.empresa_fiscais enable row level security;

drop policy if exists "fiscais_select_authenticated" on public.fiscais;
create policy "fiscais_select_authenticated" on public.fiscais
for select to authenticated
using (true);

drop policy if exists "fiscais_write_authenticated" on public.fiscais;
create policy "fiscais_write_authenticated" on public.fiscais
for all to authenticated
using (true)
with check (true);

drop policy if exists "empresa_fiscais_select_authenticated" on public.empresa_fiscais;
create policy "empresa_fiscais_select_authenticated" on public.empresa_fiscais
for select to authenticated
using (true);

drop policy if exists "empresa_fiscais_write_authenticated" on public.empresa_fiscais;
create policy "empresa_fiscais_write_authenticated" on public.empresa_fiscais
for all to authenticated
using (true)
with check (true);
