-- Projeto oficial: gduogeegnhfimuhxfmfc
-- Execute no SQL Editor do Supabase e rode o script inteiro.

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  cnpj text not null,
  fiscal text null,
  responsible text null,
  phone text null,
  email text null,
  start_date date null,
  end_date date null,
  status text not null default 'Ativa',
  contract_number text null,
  risk text null default 'Medio',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  name text not null,
  cpf text not null,
  job_role text not null,
  aso_validity date null,
  training_validity date null,
  document_status text not null default 'Pendente',
  address text null,
  notes text null,
  hiring_status text not null default 'Em analise',
  registration text null,
  manager text null,
  exception_reason text null,
  exception_deadline date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  employee_id bigint null references public.employees(id) on delete set null,
  type text not null,
  due_date date null,
  status text not null default 'Pendente',
  notes text null,
  file_path text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.historico (
  id uuid primary key default gen_random_uuid(),
  entidade_tipo text not null,
  entidade_id text not null,
  acao text not null,
  status_anterior text null,
  status_novo text null,
  usuario_id bigint null references public.usuarios(id) on delete set null,
  usuario_nome text null,
  observacao text null,
  criado_em timestamptz not null default now()
);

alter table public.usuarios
  add column if not exists auth_user_id uuid null references auth.users(id) on delete set null;

create unique index if not exists usuarios_auth_user_id_uidx
  on public.usuarios(auth_user_id)
  where auth_user_id is not null;

drop table if exists public.empresa_fiscais cascade;
drop table if exists public.fiscais cascade;

create table public.fiscais (
  id bigint generated by default as identity primary key,
  usuario_id bigint null references public.usuarios(id) on delete set null,
  auth_user_id uuid null references auth.users(id) on delete set null,
  nome text not null,
  email text null,
  matricula text null,
  telefone text null,
  setor text null,
  status text not null default 'sem_acesso' check (status in ('sem_acesso', 'com_acesso', 'inativo')),
  ativo boolean not null default true,
  data_fim timestamptz null,
  motivo_inativacao text null,
  substituto_id bigint null references public.fiscais(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.empresa_fiscais (
  empresa_id bigint not null references public.companies(id) on delete cascade,
  fiscal_id bigint not null references public.fiscais(id) on delete cascade,
  ativo boolean not null default true,
  data_inicio timestamptz not null default now(),
  data_fim timestamptz null,
  created_at timestamptz not null default now(),
  primary key (empresa_id, fiscal_id, data_inicio)
);

create index if not exists companies_status_idx on public.companies(status);
create index if not exists companies_contract_number_idx on public.companies(contract_number);
create index if not exists employees_company_id_idx on public.employees(company_id);
create index if not exists employees_cpf_idx on public.employees(cpf);
create index if not exists employees_hiring_status_idx on public.employees(hiring_status);
create index if not exists documents_company_id_idx on public.documents(company_id);
create index if not exists documents_employee_id_idx on public.documents(employee_id);
create index if not exists documents_status_idx on public.documents(status);
create index if not exists historico_entidade_idx on public.historico(entidade_tipo, entidade_id);
create index if not exists historico_criado_em_idx on public.historico(criado_em desc);
create index if not exists fiscais_usuario_id_idx on public.fiscais(usuario_id);
create index if not exists fiscais_auth_user_id_idx on public.fiscais(auth_user_id);
create index if not exists fiscais_status_idx on public.fiscais(status);
create index if not exists fiscais_email_idx on public.fiscais(lower(email));
create index if not exists empresa_fiscais_empresa_id_idx on public.empresa_fiscais(empresa_id);
create index if not exists empresa_fiscais_fiscal_id_idx on public.empresa_fiscais(fiscal_id);
create index if not exists empresa_fiscais_ativo_idx on public.empresa_fiscais(ativo);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_companies_updated_at on public.companies;
create trigger touch_companies_updated_at before update on public.companies
for each row execute function public.touch_updated_at();

drop trigger if exists touch_employees_updated_at on public.employees;
create trigger touch_employees_updated_at before update on public.employees
for each row execute function public.touch_updated_at();

drop trigger if exists touch_documents_updated_at on public.documents;
create trigger touch_documents_updated_at before update on public.documents
for each row execute function public.touch_updated_at();

drop trigger if exists touch_fiscais_updated_at on public.fiscais;
create trigger touch_fiscais_updated_at before update on public.fiscais
for each row execute function public.touch_updated_at();

alter table public.companies enable row level security;
alter table public.employees enable row level security;
alter table public.documents enable row level security;
alter table public.historico enable row level security;
alter table public.fiscais enable row level security;
alter table public.empresa_fiscais enable row level security;

drop policy if exists "companies_select_authenticated" on public.companies;
create policy "companies_select_authenticated" on public.companies
for select to authenticated
using (true);

drop policy if exists "companies_write_authenticated" on public.companies;
create policy "companies_write_authenticated" on public.companies
for all to authenticated
using (true)
with check (true);

drop policy if exists "employees_select_authenticated" on public.employees;
create policy "employees_select_authenticated" on public.employees
for select to authenticated
using (true);

drop policy if exists "employees_write_authenticated" on public.employees;
create policy "employees_write_authenticated" on public.employees
for all to authenticated
using (true)
with check (true);

drop policy if exists "documents_select_authenticated" on public.documents;
create policy "documents_select_authenticated" on public.documents
for select to authenticated
using (true);

drop policy if exists "documents_write_authenticated" on public.documents;
create policy "documents_write_authenticated" on public.documents
for all to authenticated
using (true)
with check (true);

drop policy if exists "historico_select_authenticated" on public.historico;
create policy "historico_select_authenticated" on public.historico
for select to authenticated
using (true);

drop policy if exists "historico_insert_authenticated" on public.historico;
create policy "historico_insert_authenticated" on public.historico
for insert to authenticated
with check (true);

drop policy if exists "fiscais_select_authenticated" on public.fiscais;
create policy "fiscais_select_authenticated" on public.fiscais
for select to authenticated
using (true);

drop policy if exists "fiscais_write_authenticated" on public.fiscais;
create policy "fiscais_write_authenticated" on public.fiscais
for all to authenticated
using (true)
with check (true);

drop policy if exists "empresa_fiscais_select_authenticated" on public.empresa_fiscais;
create policy "empresa_fiscais_select_authenticated" on public.empresa_fiscais
for select to authenticated
using (true);

drop policy if exists "empresa_fiscais_write_authenticated" on public.empresa_fiscais;
create policy "empresa_fiscais_write_authenticated" on public.empresa_fiscais
for all to authenticated
using (true)
with check (true);

notify pgrst, 'reload schema';
