-- Projeto oficial: gduogeegnhfimuhxfmfc
-- SQL preservador: nao usa comandos destrutivos e nao apaga dados existentes.
-- Execute no SQL Editor do Supabase e rode o script inteiro.

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  cnpj text not null,
  fiscal text null,
  responsible text null,
  phone text null,
  email text null,
  start_date date null,
  end_date date null,
  status text not null default 'Ativa',
  contract_number text null,
  risk text null default 'Medio',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.companies
  add column if not exists fiscal_id bigint null,
  add column if not exists fiscais_adicionais jsonb not null default '[]'::jsonb,
  add column if not exists nome_fantasia text null,
  add column if not exists codigo_empresa text null,
  add column if not exists codigo_filial text null,
  add column if not exists centro_custo text null,
  add column if not exists endereco text null,
  add column if not exists municipio text null,
  add column if not exists uf text null,
  add column if not exists contato_principal text null,
  add column if not exists responsavel_legal text null,
  add column if not exists observacoes text null;

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  name text not null,
  cpf text not null,
  job_role text not null,
  aso_validity date null,
  training_validity date null,
  document_status text not null default 'Pendente',
  address text null,
  notes text null,
  hiring_status text not null default 'Em analise',
  registration text null,
  manager text null,
  exception_reason text null,
  exception_deadline date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.employees
  add column if not exists company_id bigint null,
  add column if not exists name text null,
  add column if not exists cpf text null,
  add column if not exists job_role text null,
  add column if not exists aso_validity date null,
  add column if not exists training_validity date null,
  add column if not exists document_status text null default 'Pendente',
  add column if not exists address text null,
  add column if not exists notes text null,
  add column if not exists hiring_status text null default 'Em analise',
  add column if not exists registration text null,
  add column if not exists manager text null,
  add column if not exists exception_reason text null,
  add column if not exists exception_deadline date null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  employee_id bigint null references public.employees(id),
  type text not null,
  due_date date null,
  status text not null default 'Pendente',
  notes text null,
  file_path text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.documents
  add column if not exists company_id bigint null,
  add column if not exists employee_id bigint null,
  add column if not exists type text null,
  add column if not exists due_date date null,
  add column if not exists status text null default 'Pendente',
  add column if not exists notes text null,
  add column if not exists file_path text null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.historico (
  id uuid primary key default gen_random_uuid(),
  entidade_tipo text not null,
  entidade_id text not null,
  acao text not null,
  status_anterior text null,
  status_novo text null,
  usuario_id bigint null references public.usuarios(id),
  usuario_nome text null,
  observacao text null,
  criado_em timestamptz not null default now()
);

alter table public.historico
  add column if not exists entidade_tipo text null,
  add column if not exists entidade_id text null,
  add column if not exists acao text null,
  add column if not exists status_anterior text null,
  add column if not exists status_novo text null,
  add column if not exists usuario_id bigint null,
  add column if not exists usuario_nome text null,
  add column if not exists observacao text null,
  add column if not exists criado_em timestamptz not null default now();

alter table public.usuarios
  add column if not exists auth_user_id uuid null references auth.users(id);

create unique index if not exists usuarios_auth_user_id_uidx
  on public.usuarios(auth_user_id)
  where auth_user_id is not null;

create table if not exists public.fiscais (
  id bigint generated by default as identity primary key,
  usuario_id bigint null references public.usuarios(id),
  auth_user_id uuid null references auth.users(id),
  nome text not null,
  email text null,
  matricula text null,
  telefone text null,
  setor text null,
  status text not null default 'sem_acesso',
  ativo boolean not null default true,
  data_fim timestamptz null,
  motivo_inativacao text null,
  substituto_id bigint null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.fiscais
  add column if not exists usuario_id bigint null,
  add column if not exists auth_user_id uuid null,
  add column if not exists nome text null,
  add column if not exists email text null,
  add column if not exists matricula text null,
  add column if not exists telefone text null,
  add column if not exists setor text null,
  add column if not exists status text null default 'sem_acesso',
  add column if not exists ativo boolean not null default true,
  add column if not exists data_fim timestamptz null,
  add column if not exists motivo_inativacao text null,
  add column if not exists substituto_id bigint null,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.empresa_fiscais (
  empresa_id bigint not null references public.companies(id),
  fiscal_id bigint not null references public.fiscais(id),
  ativo boolean not null default true,
  data_inicio timestamptz not null default now(),
  data_fim timestamptz null,
  created_at timestamptz not null default now(),
  primary key (empresa_id, fiscal_id, data_inicio)
);

alter table public.empresa_fiscais
  add column if not exists empresa_id bigint null,
  add column if not exists fiscal_id bigint null,
  add column if not exists ativo boolean not null default true,
  add column if not exists data_inicio timestamptz not null default now(),
  add column if not exists data_fim timestamptz null,
  add column if not exists created_at timestamptz not null default now();

create index if not exists companies_status_idx on public.companies(status);
create index if not exists companies_contract_number_idx on public.companies(contract_number);
create index if not exists companies_fiscal_id_idx on public.companies(fiscal_id);
create index if not exists employees_company_id_idx on public.employees(company_id);
create index if not exists employees_cpf_idx on public.employees(cpf);
create index if not exists employees_hiring_status_idx on public.employees(hiring_status);
create index if not exists documents_company_id_idx on public.documents(company_id);
create index if not exists documents_employee_id_idx on public.documents(employee_id);
create index if not exists documents_status_idx on public.documents(status);
create index if not exists historico_entidade_idx on public.historico(entidade_tipo, entidade_id);
create index if not exists historico_criado_em_idx on public.historico(criado_em desc);
create index if not exists fiscais_usuario_id_idx on public.fiscais(usuario_id);
create index if not exists fiscais_auth_user_id_idx on public.fiscais(auth_user_id);
create index if not exists fiscais_status_idx on public.fiscais(status);
create index if not exists fiscais_email_idx on public.fiscais(lower(email));
create index if not exists empresa_fiscais_empresa_id_idx on public.empresa_fiscais(empresa_id);
create index if not exists empresa_fiscais_fiscal_id_idx on public.empresa_fiscais(fiscal_id);
create index if not exists empresa_fiscais_ativo_idx on public.empresa_fiscais(ativo);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'touch_companies_updated_at'
      and tgrelid = 'public.companies'::regclass
  ) then
    create trigger touch_companies_updated_at
    before update on public.companies
    for each row execute function public.touch_updated_at();
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'touch_employees_updated_at'
      and tgrelid = 'public.employees'::regclass
  ) then
    create trigger touch_employees_updated_at
    before update on public.employees
    for each row execute function public.touch_updated_at();
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'touch_documents_updated_at'
      and tgrelid = 'public.documents'::regclass
  ) then
    create trigger touch_documents_updated_at
    before update on public.documents
    for each row execute function public.touch_updated_at();
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'touch_fiscais_updated_at'
      and tgrelid = 'public.fiscais'::regclass
  ) then
    create trigger touch_fiscais_updated_at
    before update on public.fiscais
    for each row execute function public.touch_updated_at();
  end if;
end $$;

alter table public.companies enable row level security;
alter table public.employees enable row level security;
alter table public.documents enable row level security;
alter table public.historico enable row level security;
alter table public.fiscais enable row level security;
alter table public.empresa_fiscais enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'companies'
      and policyname = 'companies_select_authenticated'
  ) then
    create policy "companies_select_authenticated" on public.companies
    for select to authenticated
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'companies'
      and policyname = 'companies_write_authenticated'
  ) then
    create policy "companies_write_authenticated" on public.companies
    for all to authenticated
    using (true)
    with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'employees'
      and policyname = 'employees_select_authenticated'
  ) then
    create policy "employees_select_authenticated" on public.employees
    for select to authenticated
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'employees'
      and policyname = 'employees_write_authenticated'
  ) then
    create policy "employees_write_authenticated" on public.employees
    for all to authenticated
    using (true)
    with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'documents'
      and policyname = 'documents_select_authenticated'
  ) then
    create policy "documents_select_authenticated" on public.documents
    for select to authenticated
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'documents'
      and policyname = 'documents_write_authenticated'
  ) then
    create policy "documents_write_authenticated" on public.documents
    for all to authenticated
    using (true)
    with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'historico'
      and policyname = 'historico_select_authenticated'
  ) then
    create policy "historico_select_authenticated" on public.historico
    for select to authenticated
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'historico'
      and policyname = 'historico_insert_authenticated'
  ) then
    create policy "historico_insert_authenticated" on public.historico
    for insert to authenticated
    with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'fiscais'
      and policyname = 'fiscais_select_authenticated'
  ) then
    create policy "fiscais_select_authenticated" on public.fiscais
    for select to authenticated
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'fiscais'
      and policyname = 'fiscais_write_authenticated'
  ) then
    create policy "fiscais_write_authenticated" on public.fiscais
    for all to authenticated
    using (true)
    with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'empresa_fiscais'
      and policyname = 'empresa_fiscais_select_authenticated'
  ) then
    create policy "empresa_fiscais_select_authenticated" on public.empresa_fiscais
    for select to authenticated
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'empresa_fiscais'
      and policyname = 'empresa_fiscais_write_authenticated'
  ) then
    create policy "empresa_fiscais_write_authenticated" on public.empresa_fiscais
    for all to authenticated
    using (true)
    with check (true);
  end if;
end $$;

notify pgrst, 'reload schema';
