create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  auth_user_id uuid null references auth.users(id) on delete set null,
  nome text not null,
  email text not null unique,
  perfil text not null check (
    perfil in (
      'administrador',
      'fiscal',
      'medicina',
      'ehs',
      'patrimonial',
      'fornecedor',
      'visitante'
    )
  ),
  empresa_id uuid null references public.companies(id) on delete set null,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists usuarios_perfil_idx on public.usuarios (perfil);
create index if not exists usuarios_empresa_id_idx on public.usuarios (empresa_id);
create unique index if not exists usuarios_auth_user_id_uidx on public.usuarios(auth_user_id) where auth_user_id is not null;
